- targets:
    - 203.0.113.170:9101
  labels:
    instance: jetmon-v1.example.com
    role: service
    stack: jetmon
- targets:
    - 203.0.113.171:9101
  labels:
    instance: jetmon-v2.example.com
    role: service
    stack: jetmon
- targets:
    - 203.0.113.175:9101
  labels:
    instance: jetmon-extra-1.example.com
    role: service
    stack: jetmon
- targets:
    - 203.0.113.176:9101
  labels:
    instance: jetmon-extra-2.example.com
    role: service
    stack: jetmon
- targets:
    - 203.0.113.173:9101
  labels:
    instance: jetmon-lab-2.example.com
    role: vm
    stack: jetmon
- targets:
    - 203.0.113.67:9101
  labels:
    instance: monitoring.example.com
    role: monitoring
    stack: jetmon
