- targets:
    - 203.0.113.170:9256
  labels:
    instance: jetmon-v1.example.com
    role: service
    stack: jetmon
- targets:
    - 203.0.113.171:9256
  labels:
    instance: jetmon-v2.example.com
    role: service
    stack: jetmon
